### ISSUE TITLE
From sender Email

### ISSUE THREAD

**Issue by luluni83** [YieldStudio/laravel-mailjet-notifier#4]
According to Mailjet API, FROM sender must be an array, not an array of array like TO or CC fields.
So line 92 of MailjetEmailMessage class, you must remove the brackets to change 
$this->from[] = [
into 
$this->from = [
Thanks for the script however.

**Comment by JamesHemery** [comment]
@dtangdev peux-tu regarder ce sujet quand tu auras un moment ?
